spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-198-252-9.compute-1.amazonaws.com
    username: dxvfyruympakms
    password: 3a3a002e45277dbee7966cdf2b5da7ed923ba02f8fbf2ae6b1c8cf443ce32224
    # In Spring boot 2, database initialization only works for embedded databases (H2, HSQLDB).
    # If you want to use it for other databases, you need to change the
    initialization-mode: always
  jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
  jpa.show-sql: true
  jpa.hibernate.ddl-auto: update
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

# https://www.baeldung.com/spring-boot-actuators
management.endpoints.web.exposure.include: '*'