spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/cmddb
    username: root
    password:
    # In Spring boot 2, database initialization only works for embedded databases (H2, HSQLDB).
    # If you want to use it for other databases, you need to change the
    initialization-mode: always
  jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  jpa.show-sql: true
  jpa.hibernate.ddl-auto: update
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
